import { mkdirSync, writeFileSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { Meilisearch } from 'meilisearch'

const MEILI_URL = process.env.MEILISEARCH_URL || 'http://localhost:7700'
const MEILI_KEY = process.env.MEILISEARCH_KEY || 'masterKey'

/**
 * Write Obsidian-friendly markdown to vault Clippings/qsearch/ folder.
 *
 * @param {Object} args
 * @param {string} args.topic - sanitized topic name
 * @param {Array<{label, query}>} args.queries
 * @param {Map} args.results - from runSweep
 * @param {Object} args.stats
 * @returns {Promise<string|null>} file path written or null if vault not configured
 */
export async function syncToObsidian ({ topic, queries, results, stats }) {
  const vaultPath = process.env.OBSIDIAN_VAULT_PATH
  if (!vaultPath) return null

  const date = new Date().toISOString().slice(0, 10)
  const filename = `${topic}_${date}.md`
  const dir = join(vaultPath, 'Clippings', 'qsearch')
  mkdirSync(dir, { recursive: true })
  const filepath = join(dir, filename)

  const client = new Meilisearch({ host: MEILI_URL, apiKey: MEILI_KEY })
  const idx = client.index('qsearch_corpus')

  // Aggregate URLs across this sweep
  const urlMap = new Map()
  for (const { label } of queries) {
    const entry = results.get(label)
    if (!entry?.ok) continue
    for (const r of entry.results || []) {
      if (!r.url) continue
      let u = urlMap.get(r.url)
      if (!u) {
        u = { url: r.url, title: r.title || '', engines: new Set(), queries: new Set() }
        urlMap.set(r.url, u)
      }
      for (const e of r.engines || []) u.engines.add(e)
      u.queries.add(label)
    }
  }

  const highTrust = [...urlMap.values()]
    .filter((u) => u.engines.size >= 3)
    .sort((a, b) => b.engines.size - a.engines.size)

  const lines = []
  lines.push('---')
  lines.push('tags:')
  lines.push('  - qsearch')
  lines.push('  - research')
  lines.push(`  - topic/${topic}`)
  lines.push(`created: ${new Date().toISOString()}`)
  lines.push(`source_dir: _raw_data/${topic}_${date}/`)
  lines.push(`url_count: ${urlMap.size}`)
  lines.push(`high_trust_count: ${highTrust.length}`)
  lines.push('---')
  lines.push('')
  lines.push(`# qsearch — ${topic}`)
  lines.push('')
  lines.push(`Generated by qsearch on ${new Date().toISOString()}.`)
  lines.push('')

  if (highTrust.length) {
    lines.push('## 🔴 High-trust URLs (engine_count ≥ 3)')
    lines.push('')
    for (const u of highTrust.slice(0, 10)) {
      lines.push(`### ${u.title.slice(0, 80) || u.url}`)
      lines.push(`- URL: ${u.url}`)
      lines.push(`- Engines: ${[...u.engines].join(', ')} (count=${u.engines.size})`)
      lines.push(`- Found in queries: ${[...u.queries].join(', ')}`)

      // Cross-topic wikilinks
      try {
        const { hits } = await idx.search('', {
          filter: `url = '${u.url.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`,
          limit: 20,
          attributesToRetrieve: ['sweep_label']
        })
        const otherTopics = new Set()
        for (const h of hits) {
          if (h.sweep_label) {
            const t = h.sweep_label.split('_')[0]
            if (t !== topic) otherTopics.add(t)
          }
        }
        if (otherTopics.size) {
          const links = [...otherTopics].map((t) => `[[qsearch/${t}]]`).join(', ')
          lines.push(`- Also in: ${links}`)
        }
      } catch {}

      lines.push('')
    }
  }

  lines.push('---', '', '## Per-query results', '')
  for (const { label, query } of queries) {
    const entry = results.get(label)
    lines.push(`### ${label} — "${query}"`)
    if (!entry?.ok) {
      lines.push(`_Failed: ${entry?.error || 'unknown'}_`, '')
      continue
    }
    const top3 = (entry.results || []).slice(0, 3)
    for (const r of top3) {
      const enginesStr = (r.engines || []).length ? ` [${r.engines.join(', ')}]` : ''
      lines.push(`- **${(r.title || '(no title)').slice(0, 80)}**${enginesStr}`)
      lines.push(`  ${r.url}`)
    }
    lines.push('')
  }

  lines.push('---', '', '## Stats', '')
  lines.push(`- Queries: ${queries.length}`)
  lines.push(`- Unique URLs: ${urlMap.size}`)
  lines.push(`- High-trust (engine ≥ 3): ${highTrust.length}`)
  lines.push(`- Duration: ${((stats.duration_ms || 0) / 1000).toFixed(1)}s`)

  writeFileSync(filepath, lines.join('\n'), 'utf8')
  return filepath
}

/**
 * Append sweep entry to daily research log in vault root.
 */
export async function appendDailyLog ({ topic, queries, stats }) {
  const vaultPath = process.env.OBSIDIAN_VAULT_PATH
  if (!vaultPath) return null

  const logPath = join(vaultPath, 'qsearch_log.md')
  const date = new Date().toISOString().slice(0, 10)
  const time = new Date().toISOString().slice(11, 19)

  let existing = ''
  try { existing = readFileSync(logPath, 'utf8') } catch {}

  const dateHeader = `## ${date}`
  if (!existing.includes('# qsearch research log')) {
    existing = '# qsearch research log\n\n' + existing
  }
  if (!existing.includes(dateHeader)) {
    existing += `\n${dateHeader}\n`
  }

  const entry = `- ${time} sweep "${topic}" — ${queries.length} queries, ${stats.web_ok}/${stats.web_fail} ok/fail, ${((stats.duration_ms || 0) / 1000).toFixed(1)}s`
  existing += `${entry}\n`

  writeFileSync(logPath, existing, 'utf8')
  return logPath
}
